language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - pylint base.py
  - pylint happy_birthder_script_tests.py
  - pylint rc_tests.py
  - pylint viva_las_vegas_script_tests.py
  - pylint vote_or_die_script_tests.py

