version: "2"
services: 
  rocketchat-tests-based-on-splinter:
    image: cusdeb/rocketchat-tests-based-on-splinter
    command: "-s all"
    links:
      - "rocketchat:rocketchat"
    environment: 
      - USERNAME=admin
      - PASSWORD=qwerty12+
      - ADDR=rocketchat
      - PORT=8006
      - HOST=http://rocketchat:8006
      - BOT_NAME=meeseeks
      - BRANCH=${BRANCH}
    volumes:
      # The solution was borrowed from
      # https://github.com/elgalu/docker-selenium/issues/20#issuecomment-133011186
      - /dev/shm:/dev/shm
  rocketchat:
    image: cusdeb/rocketchat:0.70-amd64
    links: 
      - "mongodb:mongodb"
    environment:
    - PORT=8006
    - MONGO_DATABASE=rocketchat
    - MONGO_HOST=mongodb:27017
    - ROOT_URL=http://127.0.0.1:8006
  mongodb:
    image: mongo:3.2-jessie
  hubot-rocketchat:
    image: cusdeb/hubot-rocketchat:2.0-amd64
    links: 
      - "rocketchat:rocketchat"
      - "redis:redis"
    environment: 
      # Rocket.Chat
      - AUTH_ATTEMPTS=240
      - EXTERNAL_SCRIPTS=git:tolstoyevsky/hubot-viva-las-vegas,git:tolstoyevsky/hubot-vote-or-die,git:tolstoyevsky/hubot-pugme,git:tolstoyevsky/hubot-happy-birthder
      - RESPOND_TO_DM=true
      - REQUIRED_GROUPS=hr,leave-coordination
      - ROCKETCHAT_PASSSWORD=pass
      - ROCKETCHAT_URL=http://rocketchat:8006
      - ROCKETCHAT_USER=meeseeks
      # Redis
      - REDIS_URL=redis://redis:16379
      # hubot-happy-birthder
      - CREATE_BIRTHDAY_CHANNELS=true
      - HAPPY_REMINDER_SCHEDULER=*/1 * * * *
      - HUBOT_NAME=meeseeks
      - TENOR_API_KEY=TenorApiKey
      # hubot-viva-las-vegas
      - VIVA_REPORT_SCHEDULER=*/1 * * * *
      - VIVA_REMINDER_SCHEDULER=*/1 * * * *
  redis:
    image: cusdeb/redis:5.0-amd64
    environment:
    - REDIS_CONF_port=16379
